### ISSUE TITLE
Brontosaurus: `sign_up_for_event` returns 404 Not Found

### ISSUE THREAD

**Issue by dakur** [auto-mat/klub#429]
When I make `POST /api/sign_up_for_event/` request with correct payload, it returns "404 Not Found" from Geographic Admin Project. However, if I omit required `event` field, it correctly returns "400 Bad Request" – "event: toto pole je vyžadováno"

Example request:
```
curl --header "Content-Type: application/json" --header "Authorization: Bearer XXXXXXXX" --request POST --data '{"event": 13703, "first_name": "John", "last_name": "Doe", "telephone": "+420123456789","email":"john.doe@example.com","note":"something","age_group": 1970, "birth_month": 1, "birth_day": 1, "street": "Test", "city": "Test", "zip_code": "13245", "skills": "something", "additional_question_1": "test", "additional_question_2": "", "additional_question_3":"", "additional_question_4":""}' [domain name]/api/sign_up_for_event/
```

**Comment by timthelion** [comment]
This should be fixed now. There was a migration that was failing on the server.

**Comment by dakur** [comment]
It is. Thank you!

**Comment by mrkvon** [comment]
I still get a similar error response `500` below (html stripped):

```
Sorry
Page not found.
See [GeoDjango.org](http://geodjango.org/) for help and installation instructions

Credits: http://code.google.com/p/geodjango-basic-apps/
```

This happens to me when sending requests to base url `https://brontosaurus.klub-pratel.cz`. Also, the docs are currently not showing. Perhaps it's related?

If it's the test api which is working, can i get an account?
